[package]
name = "nexsearch-cli"
description = ""

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = {workspace = true}